language: python
python:
- '3.4'
cache: pip
install:
- python setup.py install
script:
- python setup.py test
deploy:
  password:
    secure: tvho6eZ48cqm0UONrUspIR0tqP/BgzGWnhMe/WOUalXCpZGDxjIhXpFOExVq39C6apDMaYdkoqTQdX0BErgPFTvKndj2D7jDgxvermnz0z7VoOWea204eNMdNQKB7PrTAY8Br3mLhrG+JlKzhILPE8Ok0F71aDkqGH3o3JKA11RUBPMf/FV6P6vI00MsnKAqUV6DIHxcz1RZZfLmKFbBjXQBtWGsfiWI+uQzJgDoNVTOs3jLFsoECtYcglFgN7JP+wl1cuPUZz9ubcYuvaZw7p1nqaeaOAqDoFVYtedqSL/+olukuU60/H3pyQt+hRF07YMiaro1JLQLXr8mImolJ6gHB3SzgnphObAl7qe+NptWd8XDS/CTlV33EbkZpH7WX3tLr+lfDIDFlOB7/TYDCWzjsD7+3HdYqCQIEAKXw5YYKEXRiatgLwmZqJ+M2K2NmH+3wPBZ42B+TvKAacQD+OvZuFktCkaE1Z7YW45Pw6UnV4JegSZdy9XbpOxCp+C+sRwGGt5Y7kDqUqwVP1qKDJumk/tVcTorSzs4j7avEXI0MJu+UtomGc9ZuPGlY9xDalhlbAGR/2K49Ui0ycFxlH+gznOi6gEEDtLemifRHnqAx4evQVGhmOcBP2NQ3iwxgF7dL4dVa3lKK00uHC/Ynn5veaYTHntLgBGQtVdNEj4=
  on:
    tags: true
    branch: master